#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

echo "[Hook] Add kpartx and its dependencies"
copy_exec /sbin/kpartx /sbin
copy_exec /sbin/dmsetup /sbin
copy_exec /sbin/sfdisk /sbin
copy_exec /sbin/parted /sbin
copy_exec /sbin/resize2fs /sbin
