#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

# Load helper functions
. /usr/share/initramfs-tools/hook-functions

echo "[Hook] Create mountpoints"
# Create directories inside initramfs
mkdir -p "${DESTDIR}/proc"
mkdir -p "${DESTDIR}/sys"
mkdir -p "${DESTDIR}/dev"
mkdir -p "${DESTDIR}/tmp"
mkdir -p "${DESTDIR}/boot"
mkdir -p "${DESTDIR}/sysroot"
