#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Symlink all available applets in /bin
for applet in $(/bin/busybox --list); do
    ln -sf busybox "${DESTDIR}/bin/${applet}"
done
