#!/bin/sh

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case $1 in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

echo "[Hook] Rename kernel image"
DESTDIR="/boot"
mv "${DESTDIR}/vmlinuz-${version}" "${DESTDIR}/zImage"